# Generated by Django 5.1.1 on 2024-10-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="access",
            field=models.CharField(
                choices=[("anyone", "Anyone"), ("email required", "Email Required")],
                default="email required",
                max_length=20,
            ),
        ),
    ]
