# Generated by Django 5.1.1 on 2024-10-02 16:56

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_alter_course_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("published", "Published"),
                            ("coming soon", "Coming Soon"),
                            ("draft", "Draft"),
                        ],
                        default="coming soon",
                        max_length=20,
                    ),
                ),
                (
                    "video",
                    cloudinary.models.CloudinaryField(
                        max_length=255, null=True, verbose_name="video"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="courses.course"
                    ),
                ),
            ],
        ),
    ]
