# Generated by Django 5.1.1 on 2024-10-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_lesson"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="video",
        ),
        migrations.AddField(
            model_name="lesson",
            name="can_preview",
            field=models.BooleanField(
                default=False,
                help_text="if user does not have access to course, can they see this?",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="status",
            field=models.CharField(
                choices=[
                    ("published", "Published"),
                    ("coming soon", "Coming Soon"),
                    ("draft", "Draft"),
                ],
                default="published",
                max_length=20,
            ),
        ),
    ]
