# Generated by Django 5.1.1 on 2024-10-02 17:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0009_alter_lesson_options_course_timestamp_course_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
