# Generated by Django 5.1.1 on 2024-10-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0010_lesson_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="public_id",
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
    ]
